### ISSUE TITLE
Bug: Decryption error between nodes

### ISSUE THREAD

**Issue by ariesunny** [qlcchain/qlc-ptm#10]
The destination node couldn't decrypt the privacy data send to it.

**Comment by coolc4** [comment]
Through code analysis and log backtracking, it is found that the cause of the problem is that the user configuration reverses the public-private key pair

1. After the config is read successfully after the server is added and started, add the validity check of public and private keys (and the way of mixing the random public and private keys to calculate the sharekey)

2. In the sendraw process, after sending, try to read the peer-to-peer receiverraw result to verify whether the sendraw is successful
